### ISSUE TITLE
AllAchievementsReceivedRewards does not execute my rewards

### ISSUE THREAD

**Issue by x1p** [PyvesB/AdvancedAchievements#1088]
### 🎆 Advanced Achievements version

8.0.0

### 🖥 Server version

1.17.1

### 🚰 Spigot username

x1p

### 𝑾 Wiki read

- [X] I have read the Wiki.

### 📁 Existing issues

- [X] I have searched existing issues.

### 🐛 Description

Once a year I organize an event on my server. Until last year I used the free version which worked okay. This year I bought AACH.
So I want to give my players a reward when all achievements are done. 

The event started and I start noticing that this final reward is not executed.
The player receives the "Concratulations" message just fine.
This setup used to work fine in older (free) versions.
There are no errors, it just won't give the player his final rewards.

Just to be clear: all achievements work and give rewards. Only the "AllAchievementsReceivedRewards" won't work.

### 📄 Server logs

```
nothing relevant. It starts fine.
```

### ⚙ Configuration

```yaml
AllAchievementsReceivedRewards:
  IncreaseMaxOxygen: 30
  Experience: 100
  Commands:
    Execute:
      - execute a couple commands
      - and another
      - Say congratilations blah  blah blah etc.
```
