### ISSUE TITLE
Feature Request - Permission Based Achievements

### ISSUE THREAD

**Issue by heckabecca** [PyvesB/AdvancedAchievements#180]
Hey Pyves! First of all, awesome plugin. Thanks for your hard work!

I am in the process of setting up achievements on my server and had an idea as I was setting things up. The way I'm doing the achievements on my server are in Levels 1-9. So example Farming - Plant Wheat Level 1...

I would love to set it up where free players can only go up to a certain level while becoming a VIP unlocks the remaining levels to complete. If there was a permission check that could be added per achievement this would allow me to set things up this way.

Possibly adding something like this:
```
Places:
  crops:
    '50':
      Permission: <required permission>
      Message: 'You earned an achievement!'
      Name: Planting_Wheat_1
      DisplayName: '&5Planting Wheat &7(Level 1)'
      Reward:
        Command: pex user PLAYER group add aach.places.plantingwheat1
        Money: 50
```

Obviously this could be an optional line to add and wouldn't be required for every achievement.

If this is something you'd be willing to add that would be amazing!
