### ISSUE TITLE
Reward display

### ISSUE THREAD

**Issue by S3nS3IW00** [PyvesB/AdvancedAchievements#287]
Hello dear Developer(s)!

Can you add custom reward list? So I can add reward title for command, example:
Reward:
 Item: diamond 10
 Command: give PLAYER diamond 5

Rewards: (In aach list gui)
- 10 Diamond
-  5 Diamond

**Comment by PyvesB** [comment]
Hello @S3nS3IW00 ,

I recommend taking a look at the [new Rewards Wiki page](https://github.com/PyvesB/AdvancedAchievements/wiki/Rewards). Since version 5.4 of the plugin, you can indeed display a custom reward title for the command (implemented by @supertassu in #263). Use something like this:
```
Reward:
  Item: diamond 10
  Command:
    Execute: give PLAYER diamond 5
    Display: 5 Diamond
```
Let us know whether this helps!

Cheers,

Pyves
