### ISSUE TITLE
Help with (Kills.zombie.Goal)

### ISSUE THREAD

**Issue by SpectreDonut** [PyvesB/AdvancedAchievements#508]
So the plugin keeps disabling because " Achievement with path (Kills.zombie.Goal) is missing its Name parameter in config.yml."

I don't know how to fix this, could anyone help?
Config:
Kills:
  zombie:
      25:
      Goal: Kill 25 zombies.
      Message: You killed 25 zombies!
      Name: kill_25_zombie
      DisplayName: The Walking Dead
      Reward:
        Command:
          Execute: crates key PLAYER challenge 1
          Display: 1 Challenge Key
      100:
      Goal: Kill 100 zombies.
      Message: You killed 100 zombies!
      Name: kill_100_zombie
      DisplayName: Zombie Muncher
      Reward:
        Command:
          Execute: crates key PLAYER rare 1
          Display: 1 Rare Key
      500:
      Goal: Kill 500 zombies.
      Message: You killed 500 zombies!
      Name: kill_500_zombie
      DisplayName: Zombie Crusher
      Reward:
        Command:
          Execute: crates key PLAYER epic 1
          Display: 1 Epic Key

**Comment by PyvesB** [comment]
Hello @SpectreDonut,

Is the indentation correct in your _config.yml_ file? It should look similar to the following:
````
Kills:
  zombie:
    25:
      Goal: Kill 25 zombies.
      Message: You killed 25 zombies!
      Name: kill_25_zombie
      DisplayName: The Walking Dead
      Reward:
        Command:
          Execute: crates key PLAYER challenge 1
          Display: 1 Challenge Key
````

Cheers,

Pyves
