### ISSUE TITLE
How to use commands to update permissions?

### ISSUE THREAD

**Issue by MrXuiryus** [PyvesB/AdvancedAchievements#595]
Hi there, I've been trying to acomplish this with the luck perms plugin but it doesn't seem to work with multiple achievements and the dev isn't getting back to me.

I'm trying to update a players permissions by giving them permission to a new tag that I've set up in deluxetags when they do something. In the case below it should give them the tag defined in the permissions node deluxetags.tag.withered and broadcast the message however neither of these work.

Is there an issue with the config below or is this just not going to work?

```
#When a specific mob is killed (specify an entity name or poweredcreeper or player, lower case).
Kills:
  wither:
    1:
      Goal: Kill the Wither
      Message: You always remember your first Wither.
      Name: kills_1_wither
      DisplayName: Withered
      Rewards:
        Command:
        Execute: broadcast PLAYER has become &e[&8[&7Withered&8]&e]&r; lp user PLAYER permission set deluxetags.tag.withered
```
