### ISSUE TITLE
How do you create achievements with mythicmobs that have levels in their display names?

### ISSUE THREAD

**Issue by DanHues** [PyvesB/AdvancedAchievements#622]
Hey, I was attempting to setup mythic mob achievements but my mobs use various levels of the same type of mob. Is there any way to create mythic mob achievements that can collect kills from mythic mobs that have levels in the display name?

Mythic mobs config
```YAML
Parasite:
  Type: SILVERFISH
  Health: 30
  Display: "§eParasite §8[§eLvl §6<mob.level>§8]"
  Damage: 20
  Faction: Undead
  HealthBar:
    Enabled: True
  Options:
    AlwaysShowName: true
    Collidable: true
    PreventItemPickup: true
    PreventOtherDrops: true
    FollowRange: 25
    MaxCombatDistance: 30
    MovementSpeed: 0.30
    Silent: true
  Drops:
    - exp 5-30 1
  LevelModifiers:
    Health: 4
    Damage: 0.6
    MovementSpeed: 0.008
  AIGoalSelectors:
    - 0 clear
    - 1 meleeattack
  AITargetSelectors:
    - 0 clear
    - 1 players
    - 2 attacker
  Skills:
    - sound{s=entity.silverfish.ambient;p=0.8} @self ~onTimer:120 0.7
    - sound{s=entity.silverfish.hurt;p=0.6} @self ~onDamaged
    - sound{s=entity.silverfish.death;p=1.2} @self ~onDeath
```

AdvancedAchievements Config
```YAML
  Parasite:
    "2500":
      Goal: Kill 2,500 Parasites.
      Message: REPLACED BY PROTOCOLLIB
      Name: kills_parasite_1
      DisplayName: Parasite Zone
    "10000":
      Goal: Kill 10,000 Parasites.
      Message: REPLACED BY PROTOCOLLIB
      Name: kills_parasite_2
      DisplayName: Parasite Destroyer
    "25000":
      Goal: Kill 25,000 Parasites.
      Message: REPLACED BY PROTOCOLLIB
      Name: kills_parasite_3
      DisplayName: Parasite killer
    "50000":
      Goal: Kill 50,000 Parasites.
      Message: REPLACED BY PROTOCOLLIB
      Name: kills_parasite_4
      DisplayName: Parasite slayer
    "100000":
      Goal: Kill 100,000 Parasites.
      Message: REPLACED BY PROTOCOLLIB
      Name: kills_parasite_5
      DisplayName: Tiny hitbox pro
```
